### ISSUE TITLE
How to change the Desktop picture style of mac os x automatically?

### ISSUE THREAD

**Issue by LathamZ** [xyangk/EarthLiveSharp#3]
This script can only change the Desktop picture right now, you need to set the style to "center" and set the background color to "black" manually in order to get a good view of it.

**Comment by xyangk** [comment]
Oh, it's a problem, I haven't find a way out.

**Comment by LathamZ** [comment]
I updated the code with an alternative method, just scale the pic to fit the screen will be fine.
